'use client';
export const dynamic='force-dynamic';
import {useSearchParams} from 'next/navigation';import {useEffect,useState,Suspense} from 'react';
function Results(){const q=useSearchParams(),origin=q.get('origin'),destination=q.get('destination'),date=q.get('departureDate'),adults=q.get('adults')||1,ages=q.getAll('childAge');const [offers,setOffers]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!origin||!destination)return; (async()=>{try{const child=ages.map(a=>`&childAge=${a}`).join('');const r=await fetch(`/api/search?origin=${origin}&destination=${destination}&departureDate=${date}&adults=${adults}${child}`);const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to search flights');setOffers(d.data?.offers||[])}catch(e){setError(e.message)}finally{setLoading(false)}})()},[origin,destination,date,adults]);
 if(loading)return <div className="loader-page"><div><div className="loader"></div><p style={{textAlign:'center',color:'var(--muted)',fontWeight:800}}>Finding the best flights…</p></div></div>;
 if(error)return <div className="page-shell"><div className="content"><div className="error-box">Search error: {error}</div><a className="outline-btn" href="/">← Back to search</a></div></div>;
 return <div className="page-shell"><header className="site-header"><nav className="nav"><a className="brand" href="/"><span className="brand-mark">✈</span> Perfect Motion</a><div className="nav-links"><a href="/">Flights</a><a href="/bookings">My bookings</a></div></nav></header><main className="content"><div className="page-top"><div><h1 className="page-title">Choose your flight</h1><div className="subtle">{origin} → {destination} · {date} · {adults} adult{adults>1?'s':''}</div></div><a className="outline-btn" href="/">Change search</a></div><div className="results-layout"><aside className="filter-card"><h3>Filter & sort</h3><div className="filter-line"><b>Recommended</b><br/>Best balance of price & convenience</div><div className="filter-line">Cheapest first</div><div className="filter-line">Fastest first</div><div className="filter-line">Non-stop only</div></aside><section>{offers.length===0?<div className="flight-card empty">No flights found for this route and date.</div>:offers.map(o=><article className="flight-card" key={o.id}><div><span className="badge">{o.owner?.name||'Airline'}</span><div className="airline">Flight option</div><div className="flight-meta">Economy · {adults} adult{adults>1?'s':''}</div></div><div><div className="route-times"><span className="time">—</span><span className="route-line"></span><span className="time">—</span></div><div className="flight-meta">Schedule details provided by airline</div></div><div className="price">{o.total_currency} {o.total_amount}<small>Taxes & fees included</small></div><div className="select-wrap"><button className="select-btn" onClick={()=>window.location.href=`/checkout?offerId=${o.id}`}>Select flight →</button></div></article>)}</section></div></main></div>}
export default function SearchPage(){return <Suspense fallback={<div className="loader-page"><div className="loader"/></div>}><Results/></Suspense>}
