'use client';
import { useEffect, useMemo, useState } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';

function money(amount,currency){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(Number(amount))}catch{return `${currency} ${amount}`}}
function time(s){return s?new Date(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}
function date(s){return s?new Date(s).toLocaleDateString([], {day:'2-digit',month:'short'}):''}
function mins(a,b){if(!a||!b)return 0; return Math.max(0,Math.round((new Date(b)-new Date(a))/60000))}
function dur(n){return `${Math.floor(n/60)}h ${n%60}m`}
function details(o){const segs=(o.slices||[]).flatMap(s=>s.segments||[]); return {segs, stops:segs.length-1, duration:mins(segs[0]?.departing_at,segs.at(-1)?.arriving_at)} }

export default function Search(){
 const sp=useSearchParams(), router=useRouter(); const [offers,setOffers]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [sort,setSort]=useState('best'); const [stops,setStops]=useState('all'); const [airline,setAirline]=useState('all'); const [maxPrice,setMaxPrice]=useState('');
 useEffect(()=>{fetch(`/api/search?${sp.toString()}`).then(r=>r.json()).then(j=>{if(!j.offers)throw new Error(j.error||'No offers');setOffers(j.offers)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[sp]);
 const airlines=[...new Set(offers.map(o=>o.owner?.name).filter(Boolean))]; const prices=offers.map(o=>Number(o.total_amount)||0); const highest=Math.ceil(Math.max(...prices,0));
 const filtered=useMemo(()=>{let x=[...offers]; if(stops!=='all')x=x.filter(o=>details(o).stops===Number(stops));if(airline!=='all')x=x.filter(o=>o.owner?.name===airline);if(maxPrice)x=x.filter(o=>Number(o.total_amount)<=Number(maxPrice));x.sort((a,b)=>sort==='price'?Number(a.total_amount)-Number(b.total_amount):sort==='duration'?details(a).duration-details(b).duration:(Number(a.total_amount)-Number(b.total_amount))*0.4+(details(a).stops-details(b).stops)*20);return x},[offers,sort,stops,airline,maxPrice]);
 if(loading)return <main className="results-shell"><header className="site-header"><div className="brand">✈ Trip Scanner <b>Hub</b></div></header><div className="loading-box">Searching live flight offers…</div></main>;
 return <main className="results-shell"><header className="site-header"><div className="brand"><span className="brand-mark">✈</span>Trip Scanner <b>Hub</b></div><button onClick={()=>router.push('/')}>← Change search</button></header><div className="results-top"><div><span className="eyebrow">FLIGHT RESULTS</span><h1>{sp.get('origin')} <span>→</span> {sp.get('destination')}</h1><p>{date(sp.get('departureDate'))}{sp.get('tripType')==='return'?` · Return ${date(sp.get('returnDate'))}`:''} · {sp.get('adults')||1} adult(s)</p></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="best">Recommended</option><option value="price">Cheapest</option><option value="duration">Fastest</option></select></div>
 {error?<div className="error">⚠ {error}</div>:<div className="results-layout"><aside className="filters"><h3>Filter flights</h3><label>Stops<select value={stops} onChange={e=>setStops(e.target.value)}><option value="all">Any stops</option><option value="0">Direct</option><option value="1">1 stop</option><option value="2">2+ stops</option></select></label><label>Airline<select value={airline} onChange={e=>setAirline(e.target.value)}><option value="all">All airlines</option>{airlines.map(a=><option key={a}>{a}</option>)}</select></label>{highest>0&&<label>Max price<input type="range" min="0" max={highest} value={maxPrice||highest} onChange={e=>setMaxPrice(e.target.value)}/><b>{money(maxPrice||highest,offers[0]?.total_currency||'GBP')}</b></label>}<button className="clear" onClick={()=>{setStops('all');setAirline('all');setMaxPrice('')}}>Clear filters</button></aside><section className="flight-list"><div className="result-count">{filtered.length} flight option{filtered.length!==1?'s':''}</div>{filtered.map((o,i)=><FlightCard key={o.id||i} offer={o} onSelect={()=>router.push(`/checkout?offerId=${encodeURIComponent(o.id)}`)}/>)}</section></div>}
 </main>
}
function FlightCard({offer,onSelect}){const d=details(offer);return <article className="flight-result"><div className="flight-main"><div className="airline"><div className="logo-box">{offer.owner?.logo_symbol_url?<img src={offer.owner.logo_symbol_url} alt=""/>:'✈'}</div><div><b>{offer.owner?.name||'Airline'}</b><small>{d.segs.map(s=>s.marketing_carrier?.iata_code?`${s.marketing_carrier.iata_code} ${s.marketing_carrier_flight_number||''}`:'').filter(Boolean).join(' · ')}</small></div></div><div className="timeline">{d.segs.map((s,i)=><div className="leg" key={i}><div><strong>{time(s.departing_at)}</strong><span>{s.origin?.iata_code}</span></div><div className="line"><small>{dur(mins(s.departing_at,s.arriving_at))}</small><i></i><small>{i<d.segs.length-1?'connection':'flight'}</small></div><div><strong>{time(s.arriving_at)}</strong><span>{s.destination?.iata_code}</span></div></div>)}</div><div className="flight-meta"><span>{d.stops===0?'Direct':`${d.stops} stop${d.stops>1?'s':''}`}</span><span>{dur(d.duration)}</span><span>🧳 Baggage varies by fare</span></div></div><div className="price-box"><small>From</small><strong>{money(offer.total_amount,offer.total_currency)}</strong><span>total for selected passengers</span><button onClick={onSelect}>Select flight →</button></div></article>}
