'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';

export default function Home(){
 const router=useRouter(); const today=new Date().toISOString().split('T')[0];
 const [tripType,setTripType]=useState('return'),[origin,setOrigin]=useState('LHR'),[destination,setDestination]=useState('AMD'),[departureDate,setDepartureDate]=useState(today),[adults,setAdults]=useState(1),[childrenAges,setChildrenAges]=useState([]),[cabin,setCabin]=useState('Economy'),[open,setOpen]=useState(false),[error,setError]=useState('');
 const total=adults+childrenAges.length;
 const setChildren=(n)=>{n=Math.max(0,Math.min(8,n)); if(adults+n>9){setError('Maximum 9 passengers per booking.');return} setError('');setChildrenAges(Array.from({length:n},(_,i)=>childrenAges[i]??5))};
 const search=(e)=>{e.preventDefault();setError('');if(departureDate<today)return setError('Departure date cannot be in the past.');if(total>9)return setError('Maximum 9 passengers per booking.');router.push(`/search?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&departureDate=${departureDate}&adults=${adults}${childrenAges.map(a=>`&childAge=${a}`).join('')}`)};
 return <div className="page-shell"><header className="site-header"><nav className="nav"><a className="brand" href="/"><span className="brand-mark">✈</span> Perfect Motion</a><div className="nav-links"><a href="/">Flights</a><a href="/bookings">My bookings</a><a className="nav-cta" href="/bookings">Manage booking</a></div></nav></header>
 <section className="hero"><div className="hero-inner"><span className="eyebrow">✦ Smart flight search</span><h1>Find your next flight at a better price.</h1><p className="hero-copy">Compare routes and choose the flight that fits your journey. Simple search, clear prices and a smoother booking experience.</p></div></section>
 <section className="search-card"><div className="trip-tabs"><button type="button" className={`trip-tab ${tripType==='return'?'active':''}`} onClick={()=>setTripType('return')}>↔ Return</button><button type="button" className={`trip-tab ${tripType==='oneway'?'active':''}`} onClick={()=>setTripType('oneway')}>→ One-way</button></div>
 {error&&<div className="error-box">⚠ {error}</div>}<form onSubmit={search}><div className="search-grid">
 <div className="field"><label>From</label><input value={origin} onChange={e=>setOrigin(e.target.value.toUpperCase())} placeholder="LHR" required/><div className="subtle">Airport code</div></div>
 <div className="field"><label>To</label><input value={destination} onChange={e=>setDestination(e.target.value.toUpperCase())} placeholder="AMD" required/><div className="subtle">Airport code</div></div>
 <div className="field"><label>Departure</label><input type="date" min={today} value={departureDate} onChange={e=>setDepartureDate(e.target.value)} required/></div>
 <div className="field passenger-wrap"><label>Travellers & cabin</label><button type="button" style={{border:0,background:'transparent',padding:0,textAlign:'left',fontWeight:800,color:'var(--ink)'}} onClick={()=>setOpen(!open)}>{total} traveller{total>1?'s':''} · {cabin}</button>{open&&<div className="passenger-panel">
 <div className="passenger-row"><div><b>Adults</b><div className="subtle">18+ years</div></div><select className="counter-select" value={adults} onChange={e=>{const n=+e.target.value;if(n+childrenAges.length<=9)setAdults(n)}}>{Array.from({length:9},(_,i)=><option key={i+1}>{i+1}</option>)}</select></div>
 <div className="passenger-row"><div><b>Children</b><div className="subtle">0–17 years</div></div><select className="counter-select" value={childrenAges.length} onChange={e=>setChildren(+e.target.value)}>{Array.from({length:10-adults},(_,i)=><option key={i}>{i}</option>)}</select></div>
 {childrenAges.map((age,i)=><div className="age-row" key={i}>Child {i+1}<select className="counter-select" value={age} onChange={e=>{const a=[...childrenAges];a[i]=+e.target.value;setChildrenAges(a)}}>{Array.from({length:18},(_,n)=><option key={n}>{n} yrs</option>)}</select></div>)}
 <div className="passenger-row"><b>Cabin</b><select className="counter-select" value={cabin} onChange={e=>setCabin(e.target.value)}><option>Economy</option><option>Premium Economy</option><option>Business</option><option>First</option></select></div><button className="done-btn" type="button" onClick={()=>setOpen(false)}>Done</button></div>}</div>
 <button className="search-button" type="submit">Search flights</button></div></form></section>
 <section className="benefits"><div className="benefit"><div className="benefit-icon">⌕</div><h3>Compare more options</h3><p>See available offers in one clean, easy-to-read search result.</p></div><div className="benefit"><div className="benefit-icon">£</div><h3>Clear pricing</h3><p>Keep the total price visible so you can choose with confidence.</p></div><div className="benefit"><div className="benefit-icon">✓</div><h3>Simple checkout</h3><p>Enter passenger details through a focused, modern booking form.</p></div></section></div>
}
