'use client';
import { useEffect,useState } from 'react';
import { useRouter,useSearchParams } from 'next/navigation';
function money(a,c){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency:c}).format(Number(a))}catch{return `${c} ${a}`}}
function t(s){return s?new Date(s).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}
export default function Checkout(){const sp=useSearchParams(),router=useRouter();const [offer,setOffer]=useState(null),[form,setForm]=useState({given_name:'',family_name:'',email:'',phone_number:'',born_on:'',gender:'m',nationality:'GB',passport_number:'',passport_expiry_date:''}),[error,setError]=useState('');
 useEffect(()=>{fetch(`/api/orders?offerId=${encodeURIComponent(sp.get('offerId')||'')}`).then(r=>r.json()).then(j=>setOffer(j.offer)).catch(e=>setError(e.message))},[sp]);
 function submit(e){e.preventDefault();setError('');if(!form.given_name||!form.family_name||!form.email||!form.born_on)return setError('Please complete all required passenger fields.');sessionStorage.setItem('tripScannerPassengers',JSON.stringify([form]));sessionStorage.setItem('tripScannerOfferId',sp.get('offerId'));router.push(`/payment?offerId=${encodeURIComponent(sp.get('offerId'))}`)}
 const segs=offer?.slices?.flatMap(s=>s.segments||[])||[];return <main className="checkout-shell"><header className="site-header"><div className="brand">✈ Trip Scanner <b>Hub</b></div><span>Passenger details</span></header><div className="checkout-grid"><section><div className="stepbar"><b>1 Passenger</b><span>2 Payment</span><span>3 Confirmation</span></div><form className="passenger-card" onSubmit={submit}><h1>Passenger details</h1><p>Enter details exactly as shown on the passport or travel document.</p>{error&&<div className="error">⚠ {error}</div>}<div className="form-grid">{[['given_name','First name *'],['family_name','Last name *'],['email','Email *'],['phone_number','Phone'],['born_on','Date of birth *'],['nationality','Nationality'],['passport_number','Passport number'],['passport_expiry_date','Passport expiry']].map(([k,l])=><label key={k}>{l}<input type={k.includes('date')||k==='born_on'?'date':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label>Gender<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="m">Male</option><option value="f">Female</option></select></label><button className="primary wide">Continue to payment →</button></form></section><aside className="summary"><h3>Booking summary</h3>{segs.map((s,i)=><div className="summary-leg" key={i}><b>{t(s.departing_at)} {s.origin?.iata_code} → {t(s.arriving_at)} {s.destination?.iata_code}</b><small>{s.marketing_carrier?.name||offer?.owner?.name} · {s.marketing_carrier_flight_number||''}</small></div>)}<div className="total"><span>Total</span><strong>{offer&&money(offer.total_amount,offer.total_currency)}</strong></div></aside></div></main>}
